### PR TITLE
Errors with chunked encoding responses

### LINKED ISSUE #59: Errors with chunked encoding responses and @adobe/aio-lib-state or @azure/core-rest-pipeline
When using @adobe/node-openwhisk-newrelic with @adobe/aio-lib-state (which internally uses @azure/core-rest-pipeline for CosmosDB requests), it will FAIL requests that come back with chunked encoding (and no content-length header).

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at httpRequest (/code/node_modules/@azure/cosmos/dist/index.js:7773:85)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async execute (/code/node_modules/@azure/cosmos/dist/index.js:7614:26)
    at async ClientContext.getDatabaseAccount (/code/node_modules/@azure/cosmos/dist/index.js:8493:37)
    at async CosmosClient.getDatabaseAccount (/code/node_modules/@azure/cosmos/dist/index.js:8897:26)
    at async GlobalEndpointManager.resolveServiceEndpoint (/code/node_modules/@azure/cosmos/dist/index.js:8716:51)
    at async ClientContext.read (/code/node_modules/@azure/cosmos/dist/index.js:8153:34)
    at async Container.read (/code/node_modules/@azure/cosmos/dist/index.js:6269:26)
    at async Container.readPartitionKeyDefinition (/code/node_modules/@azure/cosmos/dist/index.js:6324:41)'
```

The http instrumentation, namely this code https://github.com/adobe/node-openwhisk-newrelic/blob/cbbd5f86e9780cea3dea559653056618722d84f4/lib/probe/http-client.js#L250-L253

seems to be incompatible with the way the Azure http client library handles requests.

---

Sample code to reproduce:

```
const stateLib = require('@adobe/aio-lib-state')
const {NewRelic} = require('@adobe/openwhisk-newrelic')

async function main(params){

    const metrics = new NewRelic({
        newRelicEventsURL: params.newRelicEventsURL,
        newRelicApiKey: params.newRelicApiKey
    });

    try {
        let state = await stateLib.init();
        await state.put('12345', "dummy - value");
        const res = await state.get('12345');
        return {
            statusCode: 200,
            body: {data: res}
        };
    } catch (e){
        return {
            statusCode:500,
            body: {data: e}
        }
    } finally {
        await metrics.activationFinished();
    }
}

exports.main = NewRelic.instrument(main)
```

Error is triggered in aio-lib-state here: https://github.com/adobe/aio-lib-state/blob/master/lib/impl/CosmosStateStore.js#L34

### PR DESCRIPTION
**Pull request by alexkli**
Fixes #59. Replaces #60.

* fix by setting `response.readableFlowing = false` before registering our non-obtrusive `data` listener, and reset it to `null` so that it does not start streaming until client code adds its own data listener
* fix https url metric for `@azure/core-rest-pipeline` by looking at `opts.protocol || req.protocol`
* add unit tests for `@azure/core-rest-pipeline` http client
* add unit tests for no content-length/chunked response for all tested http clients
  * using `nock` with stream Readable as response to mimic chunked encoding response
* CI/Github Actions: test with Node 10.x, 12.x, 14.x and latest versions
* had to bump codecov to 3.8.3 as it ran into https://github.com/codecov/codecov-node/issues/324 with latest node (18) in github actions

### CODE REVIEW

File: lib/probe/http-client.js [hunk 1]
```diff
@@ -247,10 +247,19 @@ class HttpRequestMetrics {
...
+            response.readableFlowing = false;
+
             response.on("data", (chunk) => {
                 debug("⚡️ [response] data", chunk);
                 this.responseSize += chunk.length;
             });
+
+            // reset flowing state so that as soon as client code adds a data listener
+            // it will start consuming the stream
+            response.readableFlowing = null;
```
Comment (ekremney) [inline lib/probe/http-client.js:262]: I didn't understand the reason for setting `readableFlowing` to `null`. Docs says:

> Calling readable.pause(), readable.unpipe(), or receiving backpressure will cause the readable.readableFlowing to be set as false, temporarily halting the flowing of events but not halting the generation of data. While in this state, attaching a listener for the 'data' event will not switch readable.readableFlowing to true.


Besides, what happens if the client starts consuming before instrumentation sets `readableFlowing` to `null`? Wouldn't it cause the client to hang?

File: lib/probe/http-client.js [hunk 2]
```diff
@@ -247,10 +247,19 @@ class HttpRequestMetrics {
         // ...otherwise count actual response size as its streamed
         if (isNaN(this.responseSize)) {
             this.responseSize = 0;
+
+            // prevent stream from being read as soon as we add our 'data' listener below,
+            // leave that to the actual client code consuming the request
+            response.readableFlowing = false;
```
Comment (tmathern) [inline lib/probe/http-client.js:253]: Does this need a documentation update then?

File: test/probe/http-client.test.js [hunk 3]
```diff
@@ -82,9 +83,11 @@ function doAssertMetrics(metrics, opts) {
     assert.strictEqual(metrics.method, opts.method || "GET");
     assert.strictEqual(metrics.path, path);
     assert.strictEqual(metrics.url, opts.url || url);
-    assert.strictEqual(metrics.contentType, "application/json");
+    assert.strictEqual(metrics.contentType, opts.contentType || "application/json");
     if (!opts.ignoreServerIPAddress) {
-        assert.strictEqual(metrics.serverIPAddress, "127.0.0.1");
+        if (!["127.0.0.1","::1"].includes(metrics.serverIPAddress)) {
```
Comment (tmathern) [inline test/probe/http-client.test.js:88]: Should we add `localhost` too? 
```suggestion
        if (!["127.0.0.1","::1"].includes(metrics.serverIPAddress)) {
```

File: lib/probe/http-client.js (hunk 1 above)
Comment (alexkli) [reply lib/probe/http-client.js:262]: If you don't set it back to `null`, the stream will not start when the actual client code registers their `data` listener.

File: lib/probe/http-client.js (hunk 2 above)
Comment (alexkli) [reply lib/probe/http-client.js:253]: No. This doesn't change expected behavior, it fixes a bug where expected behavior of client code was broken.

File: test/probe/http-client.test.js (hunk 3 above)
Comment (alexkli) [reply test/probe/http-client.test.js:88]: It's IP address. In node 16 or so it changed from reporting IPv4 to IPv6 for localhost loopbacks, hence we need to support both so it works in different node versions.

**Review by tmathern — APPROVED** [review]

**Comment by alexkli** [comment]
@tmathern @jdelbick The integration tests failed with this one error - is this a known flaky one by any chance?

```
  1) 
       register and unregister tests
         registers a new journal:
     Error: Request 76Nsukwq0ccO36ac0X5KafCDzlgGMNdy timed out after 129000 ms
      at Timeout.<anonymous> (node_modules/@adobe/asset-compute-client/lib/client.js:346:24)
      at Timeout.wrapped (node_modules/wtfnode/index.js:237:27)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by tmathern** [comment]
> @tmathern @jdelbick The integration tests failed with this one error - is this a known flaky one by any chance?
> 
> ```
>   1) 
>        register and unregister tests
>          registers a new journal:
>      Error: Request 76Nsukwq0ccO36ac0X5KafCDzlgGMNdy timed out after 129000 ms
>       at Timeout.<anonymous> (node_modules/@adobe/asset-compute-client/lib/client.js:346:24)
>       at Timeout.wrapped (node_modules/wtfnode/index.js:237:27)
>       at listOnTimeout (internal/timers.js:554:17)
>       at processTimers (internal/timers.js:497:7)
> ```

Yes, it is an error we have encountered more recently. @jdelbick merged a fix-attempt today. Rerunning the tests to get this fix in should help them to pass.

**Comment by alexkli** [comment]
I pushed a fix https://github.com/adobe/node-openwhisk-newrelic/pull/61/commits/afa831e7d4dbd7b09d6eebd662bb3df80e06c9d2 for the node 10 issue above.

Waiting for a new IT run.
